/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayGameIdRouteImport } from './routes/play/$gameId'
import { Route as OverGameIdRouteImport } from './routes/over/$gameId'
import { Route as LobbyGameIdRouteImport } from './routes/lobby/$gameId'
import { Route as HostSetupRouteImport } from './routes/host/setup'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayGameIdRoute = PlayGameIdRouteImport.update({
  id: '/play/$gameId',
  path: '/play/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const OverGameIdRoute = OverGameIdRouteImport.update({
  id: '/over/$gameId',
  path: '/over/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyGameIdRoute = LobbyGameIdRouteImport.update({
  id: '/lobby/$gameId',
  path: '/lobby/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSetupRoute = HostSetupRouteImport.update({
  id: '/host/setup',
  path: '/host/setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/host/setup': typeof HostSetupRoute
  '/lobby/$gameId': typeof LobbyGameIdRoute
  '/over/$gameId': typeof OverGameIdRoute
  '/play/$gameId': typeof PlayGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/host/setup': typeof HostSetupRoute
  '/lobby/$gameId': typeof LobbyGameIdRoute
  '/over/$gameId': typeof OverGameIdRoute
  '/play/$gameId': typeof PlayGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/host/setup': typeof HostSetupRoute
  '/lobby/$gameId': typeof LobbyGameIdRoute
  '/over/$gameId': typeof OverGameIdRoute
  '/play/$gameId': typeof PlayGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/host/setup'
    | '/lobby/$gameId'
    | '/over/$gameId'
    | '/play/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/host/setup'
    | '/lobby/$gameId'
    | '/over/$gameId'
    | '/play/$gameId'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/host/setup'
    | '/lobby/$gameId'
    | '/over/$gameId'
    | '/play/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  HostSetupRoute: typeof HostSetupRoute
  LobbyGameIdRoute: typeof LobbyGameIdRoute
  OverGameIdRoute: typeof OverGameIdRoute
  PlayGameIdRoute: typeof PlayGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$gameId': {
      id: '/play/$gameId'
      path: '/play/$gameId'
      fullPath: '/play/$gameId'
      preLoaderRoute: typeof PlayGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over/$gameId': {
      id: '/over/$gameId'
      path: '/over/$gameId'
      fullPath: '/over/$gameId'
      preLoaderRoute: typeof OverGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$gameId': {
      id: '/lobby/$gameId'
      path: '/lobby/$gameId'
      fullPath: '/lobby/$gameId'
      preLoaderRoute: typeof LobbyGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/setup': {
      id: '/host/setup'
      path: '/host/setup'
      fullPath: '/host/setup'
      preLoaderRoute: typeof HostSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  HostSetupRoute: HostSetupRoute,
  LobbyGameIdRoute: LobbyGameIdRoute,
  OverGameIdRoute: OverGameIdRoute,
  PlayGameIdRoute: PlayGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
